### ISSUE TITLE
Requests Dependency

### ISSUE THREAD

**Issue by MicheleTobias** [MicheleTobias/LiteratureMapper#1]
Requests.py is required.  Perhaps it's not used in the code.  Check, then remove if possible.  Otherwise, figure out how to have it install or provide instructions for the work-around.

**Comment by wildintellect** [comment]
I checked with some Mac users and it's not a standard library included there or in OSGeo4w. So looks like we either need to include it or rewrite all the get and post requests to use the native urllib2 instead.
