### ISSUE TITLE
Update for QGIS 3.0

### ISSUE THREAD

**Issue by MicheleTobias** [MicheleTobias/LiteratureMapper#13]
Update the code to work with QGIS 3.0

https://gisforthought.com/updating-a-plugin-from-qgis-2-to-qgis-3/ 

https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

**Comment by wildintellect** [comment]
I think there are many tasks so we should make a label to track the sub-items that are part of this.

1.  Converting SIGNALS to Qt5
2.  Converting UI to Qt5

**Comment by wildintellect** [comment]
References for looking up how things work now in the API:

* https://qgis.org/pyqgis/master/
* https://qgis.org/api/

There's also a good list of changes from 2.x that broke the API:

* https://qgis.org/api/api_break.html
