### ISSUE TITLE
Add to Extra Field - Don't Overwrite

### ISSUE THREAD

**Issue by MicheleTobias** [MicheleTobias/LiteratureMapper#2]
The Zotero folks offer the suggestion that the extra field is used by other applications so clearing it out could become problematic.  They suggest adding the geometry text to a new line.  More text parsing, anyone?

**Comment by ecodiv** [comment]
I just saw that BetterBibTex writes the citation key to the extra field. That could thus indeed create conflicts. I have not clue how difficult or robust it is to add the geometry text to a new line, but it would be nice to be able to use both BetterBibTex and LiteratureMapper

**Comment by ecodiv** [comment]
As LiteratureMapper works with the online library anyway, a work around I will work with is to have a separate group library with (copies of) references I want to georeference

**Comment by MicheleTobias** [comment]
Yes, I know that erasing the extra field is a problem.  It will be a few weeks before I get the time to work on this.  LiteratureMapper is being developed on my own time, without financial support, so it's going to be slow. I suggest making a copy of the references you want to use and keeping a separate archive of full citations that are un-altered.  It's a good idea anyway since this is very much a work in progress.

**Comment by MicheleTobias** [comment]
Not overwriting the Extra Field has been implemented in [Release v0.3.2](https://github.com/MicheleTobias/LiteratureMapper/releases/tag/V0.3.2)
