### ISSUE TITLE
can not login to zotero

### ISSUE THREAD

**Issue by ecodiv** [MicheleTobias/LiteratureMapper#6]
After supplying the credentials to login on my online Zotero Databse with the LiteratureMapper, I am getting the error below. Seems something wrong with the authentication? User ID etc are correct as far as I can see though. Any idea what I am doing wrong?

Traceback (most recent call last):
              File "/home/paulo/.qgis2/python/plugins/LiteratureMapper/literature_mapper.py", line 364, in run
                data_json = data_get(self.userID, self.collectionID)
              File "/home/paulo/.qgis2/python/plugins/LiteratureMapper/literature_mapper.py", line 348, in data_get
                data_json = json.load(urllib2.urlopen(api_url))
              File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
                return _opener.open(url, data, timeout)
              File "/usr/lib/python2.7/urllib2.py", line 410, in open
                response = meth(req, response)
              File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
                'http', request, response, code, msg, hdrs)
              File "/usr/lib/python2.7/urllib2.py", line 448, in error
                return self._call_chain(_args)
              File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
                result = func(_args)
              File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
            HTTPError: HTTP Error 403: Forbidden

**Comment by MicheleTobias** [comment]
I can reproduce your error by putting in user names, etc., that I know are wrong or by leaving any of them blank.  I think there a couple of options: 1. Something is amiss in your login information.  Make sure you're not leaving out a character or leaving one of the fields blank.  2. It could be that when you tried, Zotero's API wasn't responding.  To test that, try again.  Occasionally, I found that Zotero won't let me log in online and in that case, I haven't been able to use LiteratureMapper.  3.  You need an online account.  Just having a desktop library isn't enough for this plugin to work.

**Comment by ecodiv** [comment]
Thanks for the quick reply. I do have an online account, and I am pretty sure that all the login information is correct, so I guess it is the Zotero's API not responding. I do notice once in a while it takes a while to login. I'll let you know if it works later. 

Btw, great addon. I had some correspondence a year or two back with somebody working on a similar addon. Can't find the email back, so I am not sure this was you, Alex Mandel, or somebody entirely different. In any case, not being able to do this myself, I have been waiting for somebody to implement something like this for a long time, so a big thanks :-)

**Comment by MicheleTobias** [comment]
You're welcome!  I'm glad it's useful!  Alex is my co-developer on this, so I wouldn't be surprised if you talked with him about it.  I developed it because it's something I'll be using.  I'm really glad other people are using it too.  I'd love to see your results.  If the log-in continues to be a problem, please keep me updated.  It may be something to discuss further with the Zotero folks.

**Comment by ecodiv** [comment]
Still no luck. I created a new key, full permission for access to personal library and groups, but still no luck. Not sure what to try / test otherwise :-(. 

Btw, would it be very hard, or possible at al, to implement something similar, but using the local database?

**Comment by wildintellect** [comment]
Possible but complicated, I think we looked at the local option, and the Zotero table layout is quite complicated. API being much simpler to implement. 

To debug the current issue I'm thinking we should dig up and post a url example for testing a key via a web browser to make sure the key works.

**Comment by wildintellect** [comment]
Ok, I don't think you can use your username, it has to be the numeric variant found on https://www.zotero.org/settings/keys

Example url you can try in a web browser:
https://api.zotero.org/users/<numeric only userid>/collections?key=<key you registered on the url above>&format=json

That will get you a list of your collections, where the key item for each is the Collection Key.

**Comment by MicheleTobias** [comment]
Yes, it doesn't work with your user log in like you would use to log in to the Zotero site, but rather the alphanumeric user id they assign you.  The documentation describes where to find those numbers: http://micheletobias.github.io/maps/LiteratureMapper.html

**Comment by ecodiv** [comment]
Yes, I used the correct alphanumeric user ID, as described in the documentation and got the collection keys from the API link you suggested above. I also tried different collection keys from that page, all with the same error. :-(

**Comment by wildintellect** [comment]
Does it work in a web browser with the url formatted like I posted?

**Comment by ecodiv** [comment]
Yes, it opens what I guess is a json file, with key (which are the collection keys if I understand right), version, library, etc.

**Comment by MicheleTobias** [comment]
Ok, we're making progress.  I was able to replicate the error with a test account. So it's either something hardcoded that shouldn't be or there's a permissions problem with the API key.

**Comment by MicheleTobias** [comment]
FOUND IT!!! It's the publication permissions on the account.  Log in online.  Go to Settings -> Privacy then check "Publish Entire Library".  It makes your library visible online, but doesn't necessarily allow others to change it (they would have to have your API key).

**Comment by ecodiv** [comment]
Well found :-). Bit strange you have to make the library publicly visible though. Perhaps something to take up with the Zotero devs?

**Comment by ecodiv** [comment]
Sorry, new issue. The plugin seems to only except / deal with entries for which the date is filled in with the year only. When opening, it shows all entries till the first one that has e.g., month and year, instead of only the year. Removing the month, reloading, and it shows all entries in the collection till the next entry with in the 'date' field more than the year only. This is the error message:

2015-10-30T21:54:59	1	Traceback (most recent call last):
			  File "/home/paulo/.qgis2/python/plugins/LiteratureMapper/literature_mapper.py", line 407, in run
			    year = QTableWidgetItem(record['data']['date'])
			KeyError: 'date'

**Comment by ecodiv** [comment]
And, sorry, another question / issue: is there a maximum number of references that can be loaded? It seems it only loads 25 references (which is perhaps coincidently the same number as shown per page online?).

**Comment by MicheleTobias** [comment]
I will look into this.  For now, you may want to make separate folders with 25 citations in each as a work around.  I have a couple of ideas of where the problem might be, but I won't have time for a couple of weeks to look into it.  ecodiv, you're an excellent tester and bug finder.  Keep up the good work!

**Comment by wildintellect** [comment]
Publish entire library should not be required. Testing in python, I can get records without having that enabled, however within the plugin it seems to require it. Need to debug the urls to make sure they are being requested correctly. Please move the other issue concerning number of items to a new Issue.

**Comment by wildintellect** [comment]
Found the issue, in literature_mapper.py ln 347.
``` api_url = 'https://api.zotero.org/users/%s/collections/%s/items?v=3' % (userID, collectionID) ``` 
That url call is missing the api key, key=, therefore it only works with public data. Adding the key seems to make it behave correctly without needed a Public library.

**Comment by ecodiv** [comment]
@wildintellect Great you found the solution. Something that will be implemented in the next version I presume?. 
@MicheleTobias I will move the item about number of citations to new item as suggested by Alex. And the same for the item about dates other then years only causing troubles
