### ISSUE TITLE
LiteratureMapper only loads 25 entries from a folder

### ISSUE THREAD

**Issue by ecodiv** [MicheleTobias/LiteratureMapper#8]
There seems to be a maximum number of references that can be loaded with LiteratureMapper (maximum of 25 references, wwhich is perhaps coincidently the same number as shown per page online?).

**Comment by MicheleTobias** [comment]
I've set the API call to return the maximum allowable number of records, which is 100.  It will put 100 records into the interface, minus the number of notes and attachments.  So if each record has an attachment, you'll get 50 records in the table.  I'll keep working on how to get a bigger list of citations into the tool.
